\babel@toc {ngerman}{}
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\addvspace {10\p@ }
\contentsline {Algorithmus}{\numberline {A.1}{\ignorespaces Sample algorithm\relax }}{23}{Algorithmus.A.1}
\contentsline {Algorithmus}{\numberline {A.2}{\ignorespaces Description \relax }}{24}{Algorithmus.A.1}
\addvspace {10\p@ }
